### ISSUE TITLE
modifying the collection in the scope is not detected

### ISSUE THREAD

**Issue by johaven** [SirIdeas/sirAccordion#2]
I have this function to parse and change the values in the collection:

 Object.byString = function(o, s) {
  s = s.replace(/[(\w+)]/g, '.$1'); // convert indexes to properties
    s = s.replace(/^./, '');           // strip a leading dot
    var a = s.split('.');
    while (a.length) {
        var n = a.shift();
        if (n in o) {
            o = o[n];
        } else {
            return;
        }
    }
    return o;
};

When i modify the contents like this:
 Object.byString($scope.collection, $scope.current_path).title = 'test';

$watch function in directive does not seem to detect that the variable change (even forcing a $scope.$apply ())

**Comment by johaven** [comment]
I think this is my Object.byString method should not be considered as a "collection" modification.
On $ http get all is good.

**Comment by axul** [comment]
Hi @yoyoprs  yeap!, now I see the problem, this happens when you change an internal attr of the collection an not the collection itfelf. I have to set an additional parameter to the $watch function in the directive to check the collection by value instead of reference (that should allow you to change an internal attribute of the colllection without problem). I'll be patching that soon thanks!. 

note: I did spot a problem with your function, you should validate if byString is returning the object before trying to assing 'test' to title.

note: I think you are trying to iterate trough the tree, you may have a problem with your regex (I think). do a test of it first.

**Comment by johaven** [comment]
The function is ok, copy paste removed slashes; but I get the object and can change the attributes in this way. My DOM variables are updated but not the tree.

**Comment by axul** [comment]
@yoyoprs  current version has an option for checking internal attributes of the collection, this should address your problem, 'config.watchInternalChanges', this flag must be false in case you don't need it for better performance in each digest cycle

**Comment by johaven** [comment]
Thank's you, it's works :)
